### ISSUE TITLE
Stop app

### ISSUE THREAD

**Issue by Hacker1254** [uwuclara/ReMod.Core-Updater#1]
if it's a plug in then it's ran before the mods are init, so u don't need to restart the app after u updated it

**Comment by uwuclara** [comment]
it's using Meloncoroutines which can't be run before  OnAppInit

**Comment by Hacker1254** [comment]
i forgor i made this
im wondering 
why'd you use a IEmn

**Comment by uwuclara** [comment]
first of even without IEnumerator it would need to be quit as UserLibs are loaded before plugins. This would only work when ReMod.Core is put in mods.

**Comment by Hacker1254** [comment]
LL is weird
